/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Basics.h"
#import "CLX_Primitives.h"
#import "CLX_Arrays.h"
#import "CLX_Dictionarys.h"
#import "CLX_Inheritances.h"
#import "CLX_Polymorphisms.h"
#import "CLX_Polymorphicrecursives.h"
#import "CLX_Readonlypropertys.h"
#import "CLX_Flattencomplexs.h"

/**
 * The interface for AutoRestComplexTestService class.
 */
@protocol CLX_AutoRestComplexTestServiceServiceProtocol

/**
 * Gets the CLX_BasicsProtocol object to access its operations.
 * @return the CLX_Basics object.
 */
- (id<CLX_BasicsProtocol>) basics;

/**
 * Gets the CLX_PrimitivesProtocol object to access its operations.
 * @return the CLX_Primitives object.
 */
- (id<CLX_PrimitivesProtocol>) primitives;

/**
 * Gets the CLX_ArraysProtocol object to access its operations.
 * @return the CLX_Arrays object.
 */
- (id<CLX_ArraysProtocol>) arrays;

/**
 * Gets the CLX_DictionarysProtocol object to access its operations.
 * @return the CLX_Dictionarys object.
 */
- (id<CLX_DictionarysProtocol>) dictionarys;

/**
 * Gets the CLX_InheritancesProtocol object to access its operations.
 * @return the CLX_Inheritances object.
 */
- (id<CLX_InheritancesProtocol>) inheritances;

/**
 * Gets the CLX_PolymorphismsProtocol object to access its operations.
 * @return the CLX_Polymorphisms object.
 */
- (id<CLX_PolymorphismsProtocol>) polymorphisms;

/**
 * Gets the CLX_PolymorphicrecursivesProtocol object to access its operations.
 * @return the CLX_Polymorphicrecursives object.
 */
- (id<CLX_PolymorphicrecursivesProtocol>) polymorphicrecursives;

/**
 * Gets the CLX_ReadonlypropertysProtocol object to access its operations.
 * @return the CLX_Readonlypropertys object.
 */
- (id<CLX_ReadonlypropertysProtocol>) readonlypropertys;

/**
 * Gets the CLX_FlattencomplexsProtocol object to access its operations.
 * @return the CLX_Flattencomplexs object.
 */
- (id<CLX_FlattencomplexsProtocol>) flattencomplexs;

@end

@interface CLX_AutoRestComplexTestServiceService : NSObject <CLX_AutoRestComplexTestServiceServiceProtocol>
/**
The default base URL. http://localhost:3000
*/
@property (readonly) NSString* DEFAULT_BASE_URL;
@property (readonly) NSString* key;
@property (readonly) NSDictionary* specialHeaders;

/**
 * API ID..
 */
@property  NSString* apiVersion;

+ (id<CLX_AutoRestComplexTestServiceServiceProtocol>)createWithApiVersion:(NSString*)apiVersion;
@end
