/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_AutoRestComplexTestServiceService.h"

/**
 * Initializes a new instance of the CLX_AutoRestComplexTestServiceService class.
 */
@implementation CLX_AutoRestComplexTestServiceService
- (instancetype)initWithApiVersion:(NSString*)apiVersion {
    self = [super init];
    if (self) {
        _DEFAULT_BASE_URL = @"http://localhost:3000";
        _key = @"UNDEFINED";
        _specialHeaders = @{@"ocp-apim-subscription-key" : self.key};
        _apiVersion = apiVersion;
    }
    return self;
}

+ (id<CLX_AutoRestComplexTestServiceServiceProtocol>)createWithApiVersion:(NSString*)apiVersion {
    CLX_AutoRestComplexTestServiceService* client = [[CLX_AutoRestComplexTestServiceService alloc] initWithApiVersion:apiVersion];
    return client;
}

/**
 * The CLX_Basics object to access its operations.
 */
- (id<CLX_BasicsProtocol>) basics {
     id<CLX_BasicsProtocol> op = [[CLX_Basics alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Primitives object to access its operations.
 */
- (id<CLX_PrimitivesProtocol>) primitives {
     id<CLX_PrimitivesProtocol> op = [[CLX_Primitives alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Arrays object to access its operations.
 */
- (id<CLX_ArraysProtocol>) arrays {
     id<CLX_ArraysProtocol> op = [[CLX_Arrays alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Dictionarys object to access its operations.
 */
- (id<CLX_DictionarysProtocol>) dictionarys {
     id<CLX_DictionarysProtocol> op = [[CLX_Dictionarys alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Inheritances object to access its operations.
 */
- (id<CLX_InheritancesProtocol>) inheritances {
     id<CLX_InheritancesProtocol> op = [[CLX_Inheritances alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Polymorphisms object to access its operations.
 */
- (id<CLX_PolymorphismsProtocol>) polymorphisms {
     id<CLX_PolymorphismsProtocol> op = [[CLX_Polymorphisms alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Polymorphicrecursives object to access its operations.
 */
- (id<CLX_PolymorphicrecursivesProtocol>) polymorphicrecursives {
     id<CLX_PolymorphicrecursivesProtocol> op = [[CLX_Polymorphicrecursives alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Readonlypropertys object to access its operations.
 */
- (id<CLX_ReadonlypropertysProtocol>) readonlypropertys {
     id<CLX_ReadonlypropertysProtocol> op = [[CLX_Readonlypropertys alloc] initWithService:self];
     return op;
}

/**
 * The CLX_Flattencomplexs object to access its operations.
 */
- (id<CLX_FlattencomplexsProtocol>) flattencomplexs {
     id<CLX_FlattencomplexsProtocol> op = [[CLX_Flattencomplexs alloc] initWithService:self];
     return op;
}
@end
