/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


#import "AutoRestComplexTestService.h"

/**
 * Initializes a new instance of the AutoRestComplexTestService class.
 */
@implementation AutoRestComplexTestService

    - (id) initWithApiVersion: (NSString*) apiVersion {
        self = [super init];
        if (self) {
            _DEFAULT_BASE_URL = @"http://localhost:3000";
            _apiVersion = apiVersion;
        }
        return self;
    }

    + (id<AutoRestComplexTestServiceProtocol>) createWithApiVersion: (NSString*) apiVersion {
        AutoRestComplexTestService* client = [[AutoRestComplexTestService alloc] initWithApiVersion: apiVersion];
        return client;
    }


    /**
     * The Basics object to access its operations.
     */
    - (id<BasicsProtocol>) basics {
         id<BasicsProtocol> op = [[Basics alloc] initWithService: self];
         return op;
    }


    /**
     * The Primitives object to access its operations.
     */
    - (id<PrimitivesProtocol>) primitives {
         id<PrimitivesProtocol> op = [[Primitives alloc] initWithService: self];
         return op;
    }


    /**
     * The Arrays object to access its operations.
     */
    - (id<ArraysProtocol>) arrays {
         id<ArraysProtocol> op = [[Arrays alloc] initWithService: self];
         return op;
    }


    /**
     * The Dictionarys object to access its operations.
     */
    - (id<DictionarysProtocol>) dictionarys {
         id<DictionarysProtocol> op = [[Dictionarys alloc] initWithService: self];
         return op;
    }


    /**
     * The Inheritances object to access its operations.
     */
    - (id<InheritancesProtocol>) inheritances {
         id<InheritancesProtocol> op = [[Inheritances alloc] initWithService: self];
         return op;
    }


    /**
     * The Polymorphisms object to access its operations.
     */
    - (id<PolymorphismsProtocol>) polymorphisms {
         id<PolymorphismsProtocol> op = [[Polymorphisms alloc] initWithService: self];
         return op;
    }


    /**
     * The Polymorphicrecursives object to access its operations.
     */
    - (id<PolymorphicrecursivesProtocol>) polymorphicrecursives {
         id<PolymorphicrecursivesProtocol> op = [[Polymorphicrecursives alloc] initWithService: self];
         return op;
    }


    /**
     * The Readonlypropertys object to access its operations.
     */
    - (id<ReadonlypropertysProtocol>) readonlypropertys {
         id<ReadonlypropertysProtocol> op = [[Readonlypropertys alloc] initWithService: self];
         return op;
    }


    /**
     * The Flattencomplexs object to access its operations.
     */
    - (id<FlattencomplexsProtocol>) flattencomplexs {
         id<FlattencomplexsProtocol> op = [[Flattencomplexs alloc] initWithService: self];
         return op;
    }



@end
