/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#include <AzureClientRuntime/AzureClientRuntime.h>
#import "Operations/FL_Files.h"

/**
 * The interface for AutoRestSwaggerBATFileService class.
 */
@protocol FL_AutoRestSwaggerBATFileServiceServiceProtocol

/**
 * Gets the FL_FilesProtocol object to access its operations.
 * @return the FL_Files object.
 */
- (id<FL_FilesProtocol>) files;

@end

@interface FL_AutoRestSwaggerBATFileServiceService : NSObject <FL_AutoRestSwaggerBATFileServiceServiceProtocol>
/**
The default base URL. http://localhost:3000
*/
@property (readonly) NSString* DEFAULT_BASE_URL;
@property (readonly) NSString* key;
@property (readonly) NSDictionary* specialHeaders;

+ (id<FL_AutoRestSwaggerBATFileServiceServiceProtocol>)create;
@end
