/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Product.h"

@implementation Product

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.integer forKey: @"integer"];
    [encoder encodeObject: self.string forKey: @"string"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        _integer = [decoder decodeObjectForKey:@"integer" objectClass:[AZInteger class]];
        _string = [decoder decodeObjectForKey:@"string" objectClass:[NSString class]];
    }

    return self;
}

@end
