/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "../Models/DictionaryWrapper.h"
@class OperationError;

/**
 * An protocol provides access to all Dictionarys operations
 */
@protocol DictionarysProtocol

    /**
     * Get complex types with dictionary property.
     *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getValidWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback;

    /**
     * Put complex types with dictionary property.
     *
     * @param complexBody Please put a dictionary with 5 key-value pairs: "txt":"notepad", "bmp":"mspaint", "xls":"excel", "exe":"", "":null
     * @param callback A block where OperationError is nil if the operation is successful
     * @throws IllegalArgumentException if a required parameter is not provided.
     */
    - (void) putValidWithComplexBody : (DictionaryWrapper *) complexBody withCallback : (void(^)(OperationError*)) callback;

    /**
     * Get complex types with dictionary property which is empty.
     *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getEmptyWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback;

    /**
     * Put complex types with dictionary property which is empty.
     *
     * @param complexBody Please put an empty dictionary
     * @param callback A block where OperationError is nil if the operation is successful
     * @throws IllegalArgumentException if a required parameter is not provided.
     */
    - (void) putEmptyWithComplexBody : (DictionaryWrapper *) complexBody withCallback : (void(^)(OperationError*)) callback;

    /**
     * Get complex types with dictionary property which is null.
     *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getNullWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback;

    /**
     * Get complex types with dictionary property while server doesn't provide a response payload.
     *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getNotProvidedWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback;

@end

/**
* The protocol implementation
*/
@class AutoRestComplexTestService;

@interface Dictionarys : NSObject <DictionarysProtocol>
@property (readonly) AutoRestComplexTestService* service;
- (instancetype) initWithService: (AutoRestComplexTestService *) service;
@end
