/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Dictionarys.h"
#import "Error.h"
#import "../AutoRestComplexTestService.h"

/**
 * The protocol DictionarysProtocol implementation
 */
@implementation Dictionarys

    - (instancetype) initWithService: (AutoRestComplexTestService *) service {
        if (self = [super init]) {
            _service = service;
        }

        return self;
    }

    /**
     * Get complex types with dictionary property.
    *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getValidWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback {


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/complex/dictionary/typed/valid"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"GET"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: nil];

        [RequestHelper executeRequest:__rp
                    withResponseClass:[DictionaryWrapper class]
                       withErrorClass:[Error class]
                         withCallback:^(id _Nullable result, OperationError* _Nullable error) {
            callback(result, error);
        }];

    }


    /**
     * Put complex types with dictionary property.
    *
     * @param complexBody Please put a dictionary with 5 key-value pairs: "txt":"notepad", "bmp":"mspaint", "xls":"excel", "exe":"", "":null
     * @param callback A block where OperationError is nil if the operation is successful
     * @throws IllegalArgumentException if a requred parameter is not provided.
     */
    - (void) putValidWithComplexBody : (DictionaryWrapper *) complexBody withCallback : (void(^)(OperationError*)) callback {

        if (complexBody == nil) {
            NSException *e = [NSException
                exceptionWithName: @"IllegalArgumentException"
                reason: @"Parameter complexBody is required and cannot be nil."
                userInfo: nil];
            @throw e;
        }


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/complex/dictionary/typed/valid"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"PUT"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: [JsonCoder encodeObject:complexBody]];

         [RequestHelper executeRequest:__rp
                        withErrorClass:[Error class]
                          withCallback:^(OperationError* _Nullable error) {
            callback(error);
        }];

    }


    /**
     * Get complex types with dictionary property which is empty.
    *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getEmptyWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback {


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/complex/dictionary/typed/empty"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"GET"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: nil];

        [RequestHelper executeRequest:__rp
                    withResponseClass:[DictionaryWrapper class]
                       withErrorClass:[Error class]
                         withCallback:^(id _Nullable result, OperationError* _Nullable error) {
            callback(result, error);
        }];

    }


    /**
     * Put complex types with dictionary property which is empty.
    *
     * @param complexBody Please put an empty dictionary
     * @param callback A block where OperationError is nil if the operation is successful
     * @throws IllegalArgumentException if a requred parameter is not provided.
     */
    - (void) putEmptyWithComplexBody : (DictionaryWrapper *) complexBody withCallback : (void(^)(OperationError*)) callback {

        if (complexBody == nil) {
            NSException *e = [NSException
                exceptionWithName: @"IllegalArgumentException"
                reason: @"Parameter complexBody is required and cannot be nil."
                userInfo: nil];
            @throw e;
        }


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/complex/dictionary/typed/empty"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"PUT"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: [JsonCoder encodeObject:complexBody]];

         [RequestHelper executeRequest:__rp
                        withErrorClass:[Error class]
                          withCallback:^(OperationError* _Nullable error) {
            callback(error);
        }];

    }


    /**
     * Get complex types with dictionary property which is null.
    *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getNullWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback {


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/complex/dictionary/typed/null"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"GET"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: nil];

        [RequestHelper executeRequest:__rp
                    withResponseClass:[DictionaryWrapper class]
                       withErrorClass:[Error class]
                         withCallback:^(id _Nullable result, OperationError* _Nullable error) {
            callback(result, error);
        }];

    }


    /**
     * Get complex types with dictionary property while server doesn't provide a response payload.
    *
     * @param callback A block where DictionaryWrapper is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getNotProvidedWithCallback : (void(^)(DictionaryWrapper*, OperationError*)) callback {


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/complex/dictionary/typed/notprovided"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"GET"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: nil];

        [RequestHelper executeRequest:__rp
                    withResponseClass:[DictionaryWrapper class]
                       withErrorClass:[Error class]
                         withCallback:^(id _Nullable result, OperationError* _Nullable error) {
            callback(result, error);
        }];

    }


@end
