/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "../Models/Siamese.h"
@class OperationError;

/**
 * An protocol provides access to all Inheritances operations
 */
@protocol InheritancesProtocol

    /**
     * Get complex types that extend others.
     *
     * @param callback A block where Siamese is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getValidWithCallback : (void(^)(Siamese*, OperationError*)) callback;

    /**
     * Put complex types that extend others.
     *
     * @param complexBody Please put a siamese with id=2, name="Siameee", color=green, breed=persion, which hates 2 dogs, the 1st one named "Potato" with id=1 and food="tomato", and the 2nd one named "Tomato" with id=-1 and food="french fries".
     * @param callback A block where OperationError is nil if the operation is successful
     * @throws IllegalArgumentException if a required parameter is not provided.
     */
    - (void) putValidWithComplexBody : (Siamese *) complexBody withCallback : (void(^)(OperationError*)) callback;

@end

/**
* The protocol implementation
*/
@class AutoRestComplexTestService;

@interface Inheritances : NSObject <InheritancesProtocol>
@property (readonly) AutoRestComplexTestService* service;
- (instancetype) initWithService: (AutoRestComplexTestService *) service;
@end
