/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Inheritances.h"
#import "CLX_Error.h"
#import "../CLX_AutoRestComplexTestServiceService.h"

/**
 * The protocol CLX_InheritancesProtocol implementation
 */
@implementation CLX_Inheritances

- (instancetype)initWithService:(CLX_AutoRestComplexTestServiceService *)service {
    if (self = [super init]) {
        _service = service;
    }

    return self;
}

/**
 * Get complex types that extend others.
 *
 * @param callback A block where CLX_Siamese is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getValidWithCallback:(void(^)(CLX_Siamese*, AZOperationError*))callback {

    NSString* __url = [AZRequestHelper buildUrl:self.service.DEFAULT_BASE_URL
                                       withPath:@"/complex/inheritance/valid"
                                 withPathParams:@{}
                                withQueryParams:@{}];
    AZRequestParameters* __rp = [AZRequestParameters createWithUrl:__url
                                                        withMethod:@"GET"
                                                       withHeaders:@{@"Content-Type":@"application/json; charset=utf-8"}
                                                          withBody:nil];
    [__rp withSpecialHeaders:self.service.specialHeaders];
    [AZRequestHelper executeRequest:__rp
                  withResponseClass:[CLX_Siamese class]
                     withErrorClass:[CLX_Error class]
                       withCallback:^(id _Nullable result, AZOperationError* _Nullable error) {
        callback(result, error);
    }];
}

/**
 * Put complex types that extend others.
 *
 * @param complexBody Please put a siamese with id=2, name="Siameee", color=green, breed=persion, which hates 2 dogs, the 1st one named "Potato" with id=1 and food="tomato", and the 2nd one named "Tomato" with id=-1 and food="french fries".
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a requred parameter is not provided or a rule validation has failed
 */
- (void)putValidWithComplexBody:(CLX_Siamese *)complexBody withCallback:(void(^)(AZOperationError*))callback {

    if (complexBody == nil) {
        @throw [NSException
            exceptionWithName: @"IllegalArgumentException"
            reason: @"Parameter 'complexBody' is required and cannot be nil."
            userInfo: nil];
    }
    NSString* __url = [AZRequestHelper buildUrl:self.service.DEFAULT_BASE_URL
                                       withPath:@"/complex/inheritance/valid"
                                 withPathParams:@{}
                                withQueryParams:@{}];
    AZRequestParameters* __rp = [AZRequestParameters createWithUrl:__url
                                                        withMethod:@"PUT"
                                                       withHeaders:@{@"Content-Type":@"application/json; charset=utf-8"}
                                                          withBody:[AZJsonCoder encodeObject:complexBody]];
    [__rp withSpecialHeaders:self.service.specialHeaders];
    [AZRequestHelper executeRequest:__rp
                     withErrorClass:[CLX_Error class]
                       withCallback:^(AZOperationError* _Nullable error) {
        callback(error);
    }];
}

@end
