/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "../Models/CLX_ArrayWrapper.h"
@class AZOperationError;

/**
 * An protocol provides access to all CLX_Arrays operations
 */
@protocol CLX_ArraysProtocol

/**
 * Get complex types with array property.
 *
 * @param callback A block where CLX_ArrayWrapper is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getValidWithCallback:(void(^)(CLX_ArrayWrapper*, AZOperationError*))callback;

/**
 * Put complex types with array property.
 *
 * @param complexBody Please put an array with 4 items: "1, 2, 3, 4", "", null, "&S#$(*Y", "The quick brown fox jumps over the lazy dog"
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putValidWithComplexBody:(CLX_ArrayWrapper *)complexBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get complex types with array property which is empty.
 *
 * @param callback A block where CLX_ArrayWrapper is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getEmptyWithCallback:(void(^)(CLX_ArrayWrapper*, AZOperationError*))callback;

/**
 * Put complex types with array property which is empty.
 *
 * @param complexBody Please put an empty array
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putEmptyWithComplexBody:(CLX_ArrayWrapper *)complexBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get complex types with array property while server doesn't provide a response payload.
 *
 * @param callback A block where CLX_ArrayWrapper is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getNotProvidedWithCallback:(void(^)(CLX_ArrayWrapper*, AZOperationError*))callback;

@end

/**
* The protocol implementation
*/
@class CLX_AutoRestComplexTestServiceService;

@interface CLX_Arrays : NSObject <CLX_ArraysProtocol>
@property (readonly) CLX_AutoRestComplexTestServiceService *service;
- (instancetype)initWithService:(CLX_AutoRestComplexTestServiceService *)service;
@end
