/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "../Models/CLX_DictionaryWrapper.h"
@class AZOperationError;

/**
 * An protocol provides access to all CLX_Dictionarys operations
 */
@protocol CLX_DictionarysProtocol

/**
 * Get complex types with dictionary property.
 *
 * @param callback A block where CLX_DictionaryWrapper is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getValidWithCallback:(void(^)(CLX_DictionaryWrapper*, AZOperationError*))callback;

/**
 * Put complex types with dictionary property.
 *
 * @param complexBody Please put a dictionary with 5 key-value pairs: "txt":"notepad", "bmp":"mspaint", "xls":"excel", "exe":"", "":null
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putValidWithComplexBody:(CLX_DictionaryWrapper *)complexBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get complex types with dictionary property which is empty.
 *
 * @param callback A block where CLX_DictionaryWrapper is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getEmptyWithCallback:(void(^)(CLX_DictionaryWrapper*, AZOperationError*))callback;

/**
 * Put complex types with dictionary property which is empty.
 *
 * @param complexBody Please put an empty dictionary
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putEmptyWithComplexBody:(CLX_DictionaryWrapper *)complexBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get complex types with dictionary property which is null.
 *
 * @param callback A block where CLX_DictionaryWrapper is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getNullWithCallback:(void(^)(CLX_DictionaryWrapper*, AZOperationError*))callback;

/**
 * Get complex types with dictionary property while server doesn't provide a response payload.
 *
 * @param callback A block where CLX_DictionaryWrapper is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getNotProvidedWithCallback:(void(^)(CLX_DictionaryWrapper*, AZOperationError*))callback;

@end

/**
* The protocol implementation
*/
@class CLX_AutoRestComplexTestServiceService;

@interface CLX_Dictionarys : NSObject <CLX_DictionarysProtocol>
@property (readonly) CLX_AutoRestComplexTestServiceService *service;
- (instancetype)initWithService:(CLX_AutoRestComplexTestServiceService *)service;
@end
