/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "../Models/CLX_MyBaseType.h"
@class AZOperationError;

/**
 * An protocol provides access to all CLX_Flattencomplexs operations
 */
@protocol CLX_FlattencomplexsProtocol

/**
 *
 * @param callback A block where CLX_MyBaseType is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getValidWithCallback:(void(^)(CLX_MyBaseType*, AZOperationError*))callback;

@end

/**
* The protocol implementation
*/
@class CLX_AutoRestComplexTestServiceService;

@interface CLX_Flattencomplexs : NSObject <CLX_FlattencomplexsProtocol>
@property (readonly) CLX_AutoRestComplexTestServiceService *service;
- (instancetype)initWithService:(CLX_AutoRestComplexTestServiceService *)service;
@end
