/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "../Models/CLX_ReadonlyObj.h"
@class AZOperationError;

/**
 * An protocol provides access to all CLX_Readonlypropertys operations
 */
@protocol CLX_ReadonlypropertysProtocol

/**
 * Get complex types that have readonly properties.
 *
 * @param callback A block where CLX_ReadonlyObj is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getValidWithCallback:(void(^)(CLX_ReadonlyObj*, AZOperationError*))callback;

/**
 * Put complex types that have readonly properties.
 *
 * @param complexBody the CLX_ReadonlyObj value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putValidWithComplexBody:(CLX_ReadonlyObj *)complexBody withCallback:(void(^)(AZOperationError*))callback;

@end

/**
* The protocol implementation
*/
@class CLX_AutoRestComplexTestServiceService;

@interface CLX_Readonlypropertys : NSObject <CLX_ReadonlypropertysProtocol>
@property (readonly) CLX_AutoRestComplexTestServiceService *service;
- (instancetype)initWithService:(CLX_AutoRestComplexTestServiceService *)service;
@end
