/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "Operations/ARR_Arrays.h"

/**
 * The interface for AutoRestSwaggerBATArrayService class.
 */
@protocol ARR_AutoRestSwaggerBATArrayServiceServiceProtocol

/**
 * Gets the ARR_ArraysProtocol object to access its operations.
 * @return the ARR_Arrays object.
 */
- (id<ARR_ArraysProtocol>)arrays;

@end

@interface ARR_AutoRestSwaggerBATArrayServiceService : NSObject <ARR_AutoRestSwaggerBATArrayServiceServiceProtocol>
/**
The default base URL. http://localhost:3000
*/
@property (readonly) NSString *DEFAULT_BASE_URL;
@property (readonly) NSString *key;
@property (readonly) NSDictionary *specialHeaders;

+ (id<ARR_AutoRestSwaggerBATArrayServiceServiceProtocol>)create;
@end
