/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ARR_AutoRestSwaggerBATArrayServiceService.h"

/**
 * Initializes a new instance of the ARR_AutoRestSwaggerBATArrayServiceService class.
 */
@implementation ARR_AutoRestSwaggerBATArrayServiceService
- (instancetype)init {
    self = [super init];
    if (self) {
        _DEFAULT_BASE_URL = @"http://localhost:3000";
        _key = @"UNDEFINED";
        _specialHeaders = @{@"ocp-apim-subscription-key" : self.key};
    }
    return self;
}
+ (id<ARR_AutoRestSwaggerBATArrayServiceServiceProtocol>)create {
    ARR_AutoRestSwaggerBATArrayServiceService* client = [[ARR_AutoRestSwaggerBATArrayServiceService alloc] init];
    return client;
}

/**
 * The ARR_Arrays object to access its operations.
 */
- (id<ARR_ArraysProtocol>) arrays {
     id<ARR_ArraysProtocol> op = [[ARR_Arrays alloc] initWithService:self];
     return op;
}
@end
