/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

@class OperationError;

/**
 * An protocol provides access to all Files operations
 */
@protocol FilesProtocol

    /**
     * Get file.
     *
     * @param callback A block where AZStream is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getFileWithCallback : (void(^)(AZStream*, OperationError*)) callback;

    /**
     * Get a large file.
     *
     * @param callback A block where AZStream is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getFileLargeWithCallback : (void(^)(AZStream*, OperationError*)) callback;

    /**
     * Get empty file.
     *
     * @param callback A block where AZStream is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getEmptyFileWithCallback : (void(^)(AZStream*, OperationError*)) callback;

@end

/**
* The protocol implementation
*/
@class AutoRestSwaggerBATFileService;

@interface Files : NSObject <FilesProtocol>
@property (readonly) AutoRestSwaggerBATFileService* service;
- (instancetype) initWithService: (AutoRestSwaggerBATFileService *) service;
@end
