/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Files.h"
#import "Error.h"
#import <AzureClientRuntime/AzureClientRuntime.h>
#import "../AutoRestSwaggerBATFileService.h"

/**
 * The protocol FilesProtocol implementation
 */
@implementation Files

    - (instancetype) initWithService: (AutoRestSwaggerBATFileService *) service {
        if (self = [super init]) {
            _service = service;
        }

        return self;
    }

    /**
     * Get file.
    *
     * @param callback A block where AZStream is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getFileWithCallback : (void(^)(AZStream*, OperationError*)) callback {


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/files/stream/nonempty"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"GET"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: nil];

        [RequestHelper executeRequest:__rp
                    withResponseClass:[AZStream class]
                       withErrorClass:[Error class]
                         withCallback:^(id _Nullable result, OperationError* _Nullable error) {
            callback(result, error);
        }];

    }


    /**
     * Get a large file.
    *
     * @param callback A block where AZStream is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getFileLargeWithCallback : (void(^)(AZStream*, OperationError*)) callback {


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/files/stream/verylarge"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"GET"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: nil];

        [RequestHelper executeRequest:__rp
                    withResponseClass:[AZStream class]
                       withErrorClass:[Error class]
                         withCallback:^(id _Nullable result, OperationError* _Nullable error) {
            callback(result, error);
        }];

    }


    /**
     * Get empty file.
    *
     * @param callback A block where AZStream is a result object and OperationError is nil, if the operation is successful
     */
    - (void) getEmptyFileWithCallback : (void(^)(AZStream*, OperationError*)) callback {


        NSString* __url = [RequestHelper buildUrl: self.service.DEFAULT_BASE_URL
                                         withPath: @"/files/stream/empty"
                                   withPathParams: @{}
                                  withQueryParams: @{}];

        RequestParameters* __rp = [RequestParameters createWithUrl: __url
                                                        withMethod: @"GET"
                                                       withHeaders: @{@"Content-Type" : @"application/json; charset=utf-8"}
                                                          withBody: nil];

        [RequestHelper executeRequest:__rp
                    withResponseClass:[AZStream class]
                       withErrorClass:[Error class]
                         withCallback:^(id _Nullable result, OperationError* _Nullable error) {
            callback(result, error);
        }];

    }


@end
