/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_MyDerivedType.h"

@implementation CLX_MyDerivedType
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject:self.propD1 forKey:@"propD1"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super initWithDecoder:decoder]) {
        _propD1 = [decoder decodeObjectForKey:@"propD1" objectClass:[NSString class]];
    }
    return self;
}
@end
