/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_SmartSalmon.h"

@implementation CLX_SmartSalmon
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject:self.additionalProperties forKey:@""];
    [encoder encodeObject:self.collegeDegree forKey:@"college_degree"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super initWithDecoder:decoder]) {
        _additionalProperties = [decoder decodeDictionaryForKey:@"" elementClass:[NSObject class]];
        _collegeDegree = [decoder decodeObjectForKey:@"college_degree" objectClass:[NSString class]];
    }
    return self;
}
@end
