/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_LongWrapper model.
 */
@interface CLX_LongWrapper : NSObject <AZCodable>
/**
 * The field1 property.
 */
@property AZLong *field1;
/**
 * The field2 property.
 */
@property AZLong *field2;
@end
