/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_DurationWrapper model.
 */
@interface CLX_DurationWrapper : NSObject <AZCodable>
/**
 * The field property.
 */
@property AZTimeSpan *field;
@end
