/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_Pet model.
 */
@interface CLX_Pet : NSObject <AZCodable>
/**
 * The idProperty property.
 */
@property AZInteger *idProperty;
/**
 * The name property.
 */
@property NSString *name;
@end
