/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_DoubleWrapper.h"

@implementation CLX_DoubleWrapper
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.field1 forKey:@"field1"];
    [encoder encodeObject:self.field56ZerosAfterTheDotAndNegativeZeroBeforeDotAndThisIsALongFieldNameOnPurpose forKey:@"field_56_zeros_after_the_dot_and_negative_zero_before_dot_and_this_is_a_long_field_name_on_purpose"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _field1 = [decoder decodeObjectForKey:@"field1" objectClass:[AZDouble class]];
        _field56ZerosAfterTheDotAndNegativeZeroBeforeDotAndThisIsALongFieldNameOnPurpose = [decoder decodeObjectForKey:@"field_56_zeros_after_the_dot_and_negative_zero_before_dot_and_this_is_a_long_field_name_on_purpose" objectClass:[AZDouble class]];
    }
    return self;
}
@end
