/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_Error model.
 */
@interface CLX_Error : NSObject <AZCodable>
/**
 * The status property.
 */
@property AZInteger *status;
/**
 * The message property.
 */
@property NSString *message;
@end
