/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_ByteWrapper model.
 */
@interface CLX_ByteWrapper : NSObject <AZCodable>
/**
 * The field property.
 */
@property AZByteArray *field;
@end
