/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_ArrayWrapper model.
 */
@interface CLX_ArrayWrapper : NSObject <AZCodable>
/**
 * The array property.
 */
@property NSArray<NSString*> *array;
@end
