/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_Goblinshark.h"

@implementation CLX_Goblinshark
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject:self.jawsize forKey:@"jawsize"];
    [encoder encodeObject:self.color forKey:@"color"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super initWithDecoder:decoder]) {
        _jawsize = [decoder decodeObjectForKey:@"jawsize" objectClass:[AZInteger class]];
        _color = [decoder decodeObjectForKey:@"color" objectClass:[CLX_GoblinSharkColor class]];
    }
    return self;
}
@end
