/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_CMYKColors.h"

/**
 * The CLX_Basic model.
 */
@interface CLX_Basic : NSObject <AZCodable>
/**
 * Basic Id.
 */
@property AZInteger *idProperty;
/**
 * Name property with a very long description that does not fit on a single
 * line and a line break.
 */
@property NSString *name;
/**
 * Possible values include: 'cyan', 'Magenta', 'YELLOW', 'blacK'.
 */
@property CLX_CMYKColors *color;
@end
