/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Shark.h"

/**
 * The CLX_Cookiecuttershark model.
 */
//JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
//JsonTypeName("cookiecuttershark")
@interface CLX_Cookiecuttershark : CLX_Shark <AZCodable>
@end
