/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_DateWrapper.h"

@implementation CLX_DateWrapper
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.field forKey:@"field"];
    [encoder encodeObject:self.leap forKey:@"leap"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _field = [decoder decodeObjectForKey:@"field" objectClass:[AZDate class]];
        _leap = [decoder decodeObjectForKey:@"leap" objectClass:[AZDate class]];
    }
    return self;
}
@end
