/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_Fish.h"

@implementation CLX_Fish
    - (id) initWithlength:(AZDouble *)length {
        self = [super init];
        if (self) {
            _length = length;
        }
        return self;
    }
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.species forKey:@"species"];
    [encoder encodeObject:self.length forKey:@"length"];
    [encoder encodeObject:self.siblings forKey:@"siblings"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _species = [decoder decodeObjectForKey:@"species" objectClass:[NSString class]];
        _length = [decoder decodeObjectForKey:@"length" objectClass:[AZDouble class]];
        _siblings = [decoder decodeArrayForKey:@"siblings" elementClass:[CLX_Fish class]];
    }
    return self;
}
@end
