/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_MyBaseType model.
 */
//JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
//JsonTypeName("MyBaseType")
// SubTypes: name = "Kind1", value = CLX_MyDerivedType
// Needs Flatten
@interface CLX_MyBaseType : NSObject <AZCodable>
/**
 * The propB1 property.
 */
@property NSString *propB1;
/**
 * The propBH1 property.
 */
@property NSString *propBH1;
@end
