/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_IntWrapper model.
 */
@interface CLX_IntWrapper : NSObject <AZCodable>
/**
 * The field1 property.
 */
@property AZInteger *field1;
/**
 * The field2 property.
 */
@property AZInteger *field2;
@end
