/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Pet.h"
#import "CLX_Dog.h"

/**
 * The CLX_Cat model.
 */
@interface CLX_Cat : CLX_Pet <AZCodable>
/**
 * The color property.
 */
@property NSString *color;
/**
 * The hates property.
 */
@property NSArray<CLX_Dog*> *hates;
@end
