/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_Datetimerfc1123Wrapper model.
 */
@interface CLX_Datetimerfc1123Wrapper : NSObject <AZCodable>
/**
 * The field property.
 */
@property AZDateTimeRfc1123 *field;
/**
 * The now property.
 */
@property AZDateTimeRfc1123 *now;
@end
