/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_DoubleWrapper model.
 */
@interface CLX_DoubleWrapper : NSObject <AZCodable>
/**
 * The field1 property.
 */
@property AZDouble *field1;
/**
 * The
 * field56ZerosAfterTheDotAndNegativeZeroBeforeDotAndThisIsALongFieldNameOnPurpose
 * property.
 */
@property AZDouble *field56ZerosAfterTheDotAndNegativeZeroBeforeDotAndThisIsALongFieldNameOnPurpose;
@end
