/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_DictionaryWrapper.h"

@implementation CLX_DictionaryWrapper
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.defaultProgram forKey:@"defaultProgram"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _defaultProgram = [decoder decodeDictionaryForKey:@"defaultProgram" elementClass:[NSString class]];
    }
    return self;
}
@end
