/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_Basic.h"

@implementation CLX_Basic
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.idProperty forKey:@"id"];
    [encoder encodeObject:self.name forKey:@"name"];
    [encoder encodeObject:self.color forKey:@"color"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _idProperty = [decoder decodeObjectForKey:@"id" objectClass:[AZInteger class]];
        _name = [decoder decodeObjectForKey:@"name" objectClass:[NSString class]];
        _color = [decoder decodeObjectForKey:@"color" objectClass:[CLX_CMYKColors class]];
    }
    return self;
}
@end
