/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_ArrayWrapper.h"

@implementation CLX_ArrayWrapper
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.array forKey:@"array"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _array = [decoder decodeArrayForKey:@"array" elementClass:[NSString class]];
    }
    return self;
}
@end
