/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_BooleanWrapper.h"

@implementation CLX_BooleanWrapper
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.fieldTrue forKey:@"field_true"];
    [encoder encodeObject:self.fieldFalse forKey:@"field_false"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _fieldTrue = [decoder decodeObjectForKey:@"field_true" objectClass:[AZBoolean class]];
        _fieldFalse = [decoder decodeObjectForKey:@"field_false" objectClass:[AZBoolean class]];
    }
    return self;
}
@end
