/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_DictionaryWrapper model.
 */
@interface CLX_DictionaryWrapper : NSObject <AZCodable>
/**
 * The defaultProgram property.
 */
@property NSDictionary<NSString*, NSString*> *defaultProgram;
@end
