/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Fish.h"

/**
 * The CLX_Salmon model.
 */
//JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
//JsonTypeName("salmon")
// SubTypes: name = "smart_salmon", value = CLX_SmartSalmon
@interface CLX_Salmon : CLX_Fish <AZCodable>
/**
 * The location property.
 */
@property NSString *location;
/**
 * The iswild property.
 */
@property AZBoolean *iswild;
@end
