/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_GoblinSharkColor.h"

/**
 * Defines values for CLX_GoblinSharkColor.
 */
@implementation CLX_GoblinSharkColor
+ (NSArray*)values {
    static NSArray *allValues;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        allValues = @[
            @"pink",
            @"gray",
            @"brown"
        ];
    });
    return allValues;
}
/** Enum value pink. */
+ (CLX_GoblinSharkColor*)PINK {
    return [CLX_GoblinSharkColor values][0];
}
/** Enum value gray. */
+ (CLX_GoblinSharkColor*)GRAY {
    return [CLX_GoblinSharkColor values][1];
}
/** Enum value brown. */
+ (CLX_GoblinSharkColor*)BROWN {
    return [CLX_GoblinSharkColor values][2];
}
+ (CLX_GoblinSharkColor *)fromString:(NSString *)string {
    return (CLX_GoblinSharkColor *)string;
}
+ (NSString *)toStringValue:(CLX_GoblinSharkColor *)value {
    return (NSString *)value;
}
@end
