/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Shark.h"
#import "CLX_GoblinSharkColor.h"

/**
 * The CLX_Goblinshark model.
 */
//JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
//JsonTypeName("goblin")
@interface CLX_Goblinshark : CLX_Shark <AZCodable>
/**
 * The jawsize property.
 */
@property AZInteger *jawsize;
/**
 * Colors possible. Possible values include: 'pink', 'gray', 'brown'.
 */
@property CLX_GoblinSharkColor *color;
@end
