/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_MyBaseType.h"

/**
 * The CLX_MyDerivedType model.
 */
//JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
//JsonTypeName("Kind1")
@interface CLX_MyDerivedType : CLX_MyBaseType <AZCodable>
/**
 * The propD1 property.
 */
@property NSString *propD1;
@end
