/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Fish.h"

/**
 * The CLX_Shark model.
 */
//JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
//JsonTypeName("shark")
// SubTypes: name = "sawshark", value = CLX_Sawshark
// SubTypes: name = "goblin", value = CLX_Goblinshark
// SubTypes: name = "cookiecuttershark", value = CLX_Cookiecuttershark
@interface CLX_Shark : CLX_Fish <AZCodable>
/**
 * The age property.
 */
@property AZInteger *age;
/**
 * The birthday property.
 */
@property AZDateTime *birthday;
/**
* Creates an instance of CLX_Shark class.
* @param birthday the birthday value.
*/
- (id) initWithbirthday:(AZDateTime *)birthday;
@end
