/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_ByteWrapper.h"

@implementation CLX_ByteWrapper
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.field forKey:@"field"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _field = [decoder decodeObjectForKey:@"field" objectClass:[AZByteArray class]];
    }
    return self;
}
@end
