/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "CLX_StringWrapper.h"

@implementation CLX_StringWrapper
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.field forKey:@"field"];
    [encoder encodeObject:self.empty forKey:@"empty"];
    [encoder encodeObject:self.null forKey:@"null"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _field = [decoder decodeObjectForKey:@"field" objectClass:[NSString class]];
        _empty = [decoder decodeObjectForKey:@"empty" objectClass:[NSString class]];
        _null = [decoder decodeObjectForKey:@"null" objectClass:[NSString class]];
    }
    return self;
}
@end
