/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_BooleanWrapper model.
 */
@interface CLX_BooleanWrapper : NSObject <AZCodable>
/**
 * The fieldTrue property.
 */
@property AZBoolean *fieldTrue;
/**
 * The fieldFalse property.
 */
@property AZBoolean *fieldFalse;
@end
