/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#include <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The CLX_StringWrapper model.
 */
@interface CLX_StringWrapper : NSObject <AZCodable>
/**
 * The field property.
 */
@property NSString *field;
/**
 * The empty property.
 */
@property NSString *empty;
/**
 * The null property.
 */
@property NSString *null;
@end
