/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CLX_Fish.h"

/**
 * The CLX_Fish model.
 */
//JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
//JsonTypeName("Fish")
// SubTypes: name = "salmon", value = CLX_Salmon
// SubTypes: name = "shark", value = CLX_Shark
@interface CLX_Fish : NSObject <AZCodable>
/**
 * The species property.
 */
@property NSString *species;
/**
 * The length property.
 */
@property AZDouble *length;
/**
 * The siblings property.
 */
@property NSArray<CLX_Fish*> *siblings;
/**
* Creates an instance of CLX_Fish class.
* @param length the length value.
*/
- (id) initWithlength:(AZDouble *)length;
@end
