/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "ARR_FooEnum.h"
#import "ARR_Product.h"
@class AZOperationError;

/**
 * An protocol provides access to all ARR_Arrays operations
 */
@protocol ARR_ArraysProtocol

/**
 * Get null array value.
 *
 * @param callback A block where NSArray<AZInteger*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getNullWithCallback:(void(^)(NSArray<AZInteger*>*, AZOperationError*))callback;

/**
 * Get invalid array [1, 2, 3.
 *
 * @param callback A block where NSArray<AZInteger*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getInvalidWithCallback:(void(^)(NSArray<AZInteger*>*, AZOperationError*))callback;

/**
 * Get empty array value [].
 *
 * @param callback A block where NSArray<AZInteger*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getEmptyWithCallback:(void(^)(NSArray<AZInteger*>*, AZOperationError*))callback;

/**
 * Set array value empty [].
 *
 * @param arrayBody the NSArray<NSString*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putEmptyWithArrayBody:(NSArray<NSString*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get boolean array value [true, false, false, true].
 *
 * @param callback A block where NSArray<AZBoolean*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getBooleanTfftWithCallback:(void(^)(NSArray<AZBoolean*>*, AZOperationError*))callback;

/**
 * Set array value empty [true, false, false, true].
 *
 * @param arrayBody the NSArray<AZBoolean*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putBooleanTfftWithArrayBody:(NSArray<AZBoolean*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get boolean array value [true, null, false].
 *
 * @param callback A block where NSArray<AZBoolean*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getBooleanInvalidNullWithCallback:(void(^)(NSArray<AZBoolean*>*, AZOperationError*))callback;

/**
 * Get boolean array value [true, 'boolean', false].
 *
 * @param callback A block where NSArray<AZBoolean*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getBooleanInvalidStringWithCallback:(void(^)(NSArray<AZBoolean*>*, AZOperationError*))callback;

/**
 * Get integer array value [1, -1, 3, 300].
 *
 * @param callback A block where NSArray<AZInteger*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getIntegerValidWithCallback:(void(^)(NSArray<AZInteger*>*, AZOperationError*))callback;

/**
 * Set array value empty [1, -1, 3, 300].
 *
 * @param arrayBody the NSArray<AZInteger*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putIntegerValidWithArrayBody:(NSArray<AZInteger*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get integer array value [1, null, 0].
 *
 * @param callback A block where NSArray<AZInteger*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getIntInvalidNullWithCallback:(void(^)(NSArray<AZInteger*>*, AZOperationError*))callback;

/**
 * Get integer array value [1, 'integer', 0].
 *
 * @param callback A block where NSArray<AZInteger*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getIntInvalidStringWithCallback:(void(^)(NSArray<AZInteger*>*, AZOperationError*))callback;

/**
 * Get integer array value [1, -1, 3, 300].
 *
 * @param callback A block where NSArray<AZLong*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getLongValidWithCallback:(void(^)(NSArray<AZLong*>*, AZOperationError*))callback;

/**
 * Set array value empty [1, -1, 3, 300].
 *
 * @param arrayBody the NSArray<AZLong*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putLongValidWithArrayBody:(NSArray<AZLong*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get long array value [1, null, 0].
 *
 * @param callback A block where NSArray<AZLong*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getLongInvalidNullWithCallback:(void(^)(NSArray<AZLong*>*, AZOperationError*))callback;

/**
 * Get long array value [1, 'integer', 0].
 *
 * @param callback A block where NSArray<AZLong*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getLongInvalidStringWithCallback:(void(^)(NSArray<AZLong*>*, AZOperationError*))callback;

/**
 * Get float array value [0, -0.01, 1.2e20].
 *
 * @param callback A block where NSArray<AZDouble*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getFloatValidWithCallback:(void(^)(NSArray<AZDouble*>*, AZOperationError*))callback;

/**
 * Set array value [0, -0.01, 1.2e20].
 *
 * @param arrayBody the NSArray<AZDouble*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putFloatValidWithArrayBody:(NSArray<AZDouble*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get float array value [0.0, null, -1.2e20].
 *
 * @param callback A block where NSArray<AZDouble*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getFloatInvalidNullWithCallback:(void(^)(NSArray<AZDouble*>*, AZOperationError*))callback;

/**
 * Get boolean array value [1.0, 'number', 0.0].
 *
 * @param callback A block where NSArray<AZDouble*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getFloatInvalidStringWithCallback:(void(^)(NSArray<AZDouble*>*, AZOperationError*))callback;

/**
 * Get float array value [0, -0.01, 1.2e20].
 *
 * @param callback A block where NSArray<AZDouble*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDoubleValidWithCallback:(void(^)(NSArray<AZDouble*>*, AZOperationError*))callback;

/**
 * Set array value [0, -0.01, 1.2e20].
 *
 * @param arrayBody the NSArray<AZDouble*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putDoubleValidWithArrayBody:(NSArray<AZDouble*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get float array value [0.0, null, -1.2e20].
 *
 * @param callback A block where NSArray<AZDouble*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDoubleInvalidNullWithCallback:(void(^)(NSArray<AZDouble*>*, AZOperationError*))callback;

/**
 * Get boolean array value [1.0, 'number', 0.0].
 *
 * @param callback A block where NSArray<AZDouble*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDoubleInvalidStringWithCallback:(void(^)(NSArray<AZDouble*>*, AZOperationError*))callback;

/**
 * Get string array value ['foo1', 'foo2', 'foo3'].
 *
 * @param callback A block where NSArray<NSString*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getStringValidWithCallback:(void(^)(NSArray<NSString*>*, AZOperationError*))callback;

/**
 * Set array value ['foo1', 'foo2', 'foo3'].
 *
 * @param arrayBody the NSArray<NSString*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putStringValidWithArrayBody:(NSArray<NSString*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get enum array value ['foo1', 'foo2', 'foo3'].
 *
 * @param callback A block where NSArray<ARR_FooEnum*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getEnumValidWithCallback:(void(^)(NSArray<ARR_FooEnum*>*, AZOperationError*))callback;

/**
 * Set array value ['foo1', 'foo2', 'foo3'].
 *
 * @param arrayBody the NSArray<ARR_FooEnum*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putEnumValidWithArrayBody:(NSArray<ARR_FooEnum*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get enum array value ['foo1', 'foo2', 'foo3'].
 *
 * @param callback A block where NSArray<NSString*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getStringEnumValidWithCallback:(void(^)(NSArray<NSString*>*, AZOperationError*))callback;

/**
 * Set array value ['foo1', 'foo2', 'foo3'].
 *
 * @param arrayBody the NSArray<NSString*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putStringEnumValidWithArrayBody:(NSArray<NSString*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get string array value ['foo', null, 'foo2'].
 *
 * @param callback A block where NSArray<NSString*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getStringWithNullWithCallback:(void(^)(NSArray<NSString*>*, AZOperationError*))callback;

/**
 * Get string array value ['foo', 123, 'foo2'].
 *
 * @param callback A block where NSArray<NSString*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getStringWithInvalidWithCallback:(void(^)(NSArray<NSString*>*, AZOperationError*))callback;

/**
 * Get uuid array value ['6dcc7237-45fe-45c4-8a6b-3a8a3f625652', 'd1399005-30f7-40d6-8da6-dd7c89ad34db', 'f42f6aa1-a5bc-4ddf-907e-5f915de43205'].
 *
 * @param callback A block where NSArray<NSUUID*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getUuidValidWithCallback:(void(^)(NSArray<NSUUID*>*, AZOperationError*))callback;

/**
 * Set array value  ['6dcc7237-45fe-45c4-8a6b-3a8a3f625652', 'd1399005-30f7-40d6-8da6-dd7c89ad34db', 'f42f6aa1-a5bc-4ddf-907e-5f915de43205'].
 *
 * @param arrayBody the NSArray<NSUUID*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putUuidValidWithArrayBody:(NSArray<NSUUID*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get uuid array value ['6dcc7237-45fe-45c4-8a6b-3a8a3f625652', 'foo'].
 *
 * @param callback A block where NSArray<NSUUID*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getUuidInvalidCharsWithCallback:(void(^)(NSArray<NSUUID*>*, AZOperationError*))callback;

/**
 * Get integer array value ['2000-12-01', '1980-01-02', '1492-10-12'].
 *
 * @param callback A block where NSArray<AZDate*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDateValidWithCallback:(void(^)(NSArray<AZDate*>*, AZOperationError*))callback;

/**
 * Set array value  ['2000-12-01', '1980-01-02', '1492-10-12'].
 *
 * @param arrayBody the NSArray<AZDate*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putDateValidWithArrayBody:(NSArray<AZDate*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get date array value ['2012-01-01', null, '1776-07-04'].
 *
 * @param callback A block where NSArray<AZDate*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDateInvalidNullWithCallback:(void(^)(NSArray<AZDate*>*, AZOperationError*))callback;

/**
 * Get date array value ['2011-03-22', 'date'].
 *
 * @param callback A block where NSArray<AZDate*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDateInvalidCharsWithCallback:(void(^)(NSArray<AZDate*>*, AZOperationError*))callback;

/**
 * Get date-time array value ['2000-12-01t00:00:01z', '1980-01-02T00:11:35+01:00', '1492-10-12T10:15:01-08:00'].
 *
 * @param callback A block where NSArray<AZDateTime*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDateTimeValidWithCallback:(void(^)(NSArray<AZDateTime*>*, AZOperationError*))callback;

/**
 * Set array value  ['2000-12-01t00:00:01z', '1980-01-02T00:11:35+01:00', '1492-10-12T10:15:01-08:00'].
 *
 * @param arrayBody the NSArray<AZDateTime*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putDateTimeValidWithArrayBody:(NSArray<AZDateTime*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get date array value ['2000-12-01t00:00:01z', null].
 *
 * @param callback A block where NSArray<AZDateTime*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDateTimeInvalidNullWithCallback:(void(^)(NSArray<AZDateTime*>*, AZOperationError*))callback;

/**
 * Get date array value ['2000-12-01t00:00:01z', 'date-time'].
 *
 * @param callback A block where NSArray<AZDateTime*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDateTimeInvalidCharsWithCallback:(void(^)(NSArray<AZDateTime*>*, AZOperationError*))callback;

/**
 * Get date-time array value ['Fri, 01 Dec 2000 00:00:01 GMT', 'Wed, 02 Jan 1980 00:11:35 GMT', 'Wed, 12 Oct 1492 10:15:01 GMT'].
 *
 * @param callback A block where NSArray<AZDateTimeRfc1123*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDateTimeRfc1123ValidWithCallback:(void(^)(NSArray<AZDateTimeRfc1123*>*, AZOperationError*))callback;

/**
 * Set array value  ['Fri, 01 Dec 2000 00:00:01 GMT', 'Wed, 02 Jan 1980 00:11:35 GMT', 'Wed, 12 Oct 1492 10:15:01 GMT'].
 *
 * @param arrayBody the NSArray<AZDateTimeRfc1123*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putDateTimeRfc1123ValidWithArrayBody:(NSArray<AZDateTimeRfc1123*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get duration array value ['P123DT22H14M12.011S', 'P5DT1H0M0S'].
 *
 * @param callback A block where NSArray<AZTimeSpan*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDurationValidWithCallback:(void(^)(NSArray<AZTimeSpan*>*, AZOperationError*))callback;

/**
 * Set array value  ['P123DT22H14M12.011S', 'P5DT1H0M0S'].
 *
 * @param arrayBody the NSArray<AZTimeSpan*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putDurationValidWithArrayBody:(NSArray<AZTimeSpan*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get byte array value [hex(FF FF FF FA), hex(01 02 03), hex (25, 29, 43)] with each item encoded in base64.
 *
 * @param callback A block where NSArray<AZByteArray*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getByteValidWithCallback:(void(^)(NSArray<AZByteArray*>*, AZOperationError*))callback;

/**
 * Put the array value [hex(FF FF FF FA), hex(01 02 03), hex (25, 29, 43)] with each elementencoded in base 64.
 *
 * @param arrayBody the NSArray<AZByteArray*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putByteValidWithArrayBody:(NSArray<AZByteArray*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get byte array value [hex(AB, AC, AD), null] with the first item base64 encoded.
 *
 * @param callback A block where NSArray<AZByteArray*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getByteInvalidNullWithCallback:(void(^)(NSArray<AZByteArray*>*, AZOperationError*))callback;

/**
 * Get array value ['a string that gets encoded with base64url', 'test string' 'Lorem ipsum'] with the items base64url encoded.
 *
 * @param callback A block where NSArray<AZBase64Url*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getBase64UrlWithCallback:(void(^)(NSArray<AZBase64Url*>*, AZOperationError*))callback;

/**
 * Get array of complex type null value.
 *
 * @param callback A block where NSArray<ARR_Product*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getComplexNullWithCallback:(void(^)(NSArray<ARR_Product*>*, AZOperationError*))callback;

/**
 * Get empty array of complex type [].
 *
 * @param callback A block where NSArray<ARR_Product*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getComplexEmptyWithCallback:(void(^)(NSArray<ARR_Product*>*, AZOperationError*))callback;

/**
 * Get array of complex type with null item [{'integer': 1 'string': '2'}, null, {'integer': 5, 'string': '6'}].
 *
 * @param callback A block where NSArray<ARR_Product*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getComplexItemNullWithCallback:(void(^)(NSArray<ARR_Product*>*, AZOperationError*))callback;

/**
 * Get array of complex type with empty item [{'integer': 1 'string': '2'}, {}, {'integer': 5, 'string': '6'}].
 *
 * @param callback A block where NSArray<ARR_Product*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getComplexItemEmptyWithCallback:(void(^)(NSArray<ARR_Product*>*, AZOperationError*))callback;

/**
 * Get array of complex type with [{'integer': 1 'string': '2'}, {'integer': 3, 'string': '4'}, {'integer': 5, 'string': '6'}].
 *
 * @param callback A block where NSArray<ARR_Product*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getComplexValidWithCallback:(void(^)(NSArray<ARR_Product*>*, AZOperationError*))callback;

/**
 * Put an array of complex type with values [{'integer': 1 'string': '2'}, {'integer': 3, 'string': '4'}, {'integer': 5, 'string': '6'}].
 *
 * @param arrayBody the NSArray<ARR_Product*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putComplexValidWithArrayBody:(NSArray<ARR_Product*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get a null array.
 *
 * @param callback A block where NSArray<NSArray<NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getArrayNullWithCallback:(void(^)(NSArray<NSArray<NSString*>*>*, AZOperationError*))callback;

/**
 * Get an empty array [].
 *
 * @param callback A block where NSArray<NSArray<NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getArrayEmptyWithCallback:(void(^)(NSArray<NSArray<NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of array of strings [['1', '2', '3'], null, ['7', '8', '9']].
 *
 * @param callback A block where NSArray<NSArray<NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getArrayItemNullWithCallback:(void(^)(NSArray<NSArray<NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of array of strings [['1', '2', '3'], [], ['7', '8', '9']].
 *
 * @param callback A block where NSArray<NSArray<NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getArrayItemEmptyWithCallback:(void(^)(NSArray<NSArray<NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of array of strings [['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']].
 *
 * @param callback A block where NSArray<NSArray<NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getArrayValidWithCallback:(void(^)(NSArray<NSArray<NSString*>*>*, AZOperationError*))callback;

/**
 * Put An array of array of strings [['1', '2', '3'], ['4', '5', '6'], ['7', '8', '9']].
 *
 * @param arrayBody the NSArray<NSArray<NSString*>*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putArrayValidWithArrayBody:(NSArray<NSArray<NSString*>*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

/**
 * Get an array of Dictionaries with value null.
 *
 * @param callback A block where NSArray<NSDictionary<NSString*, NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDictionaryNullWithCallback:(void(^)(NSArray<NSDictionary<NSString*, NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of Dictionaries of type <string, string> with value [].
 *
 * @param callback A block where NSArray<NSDictionary<NSString*, NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDictionaryEmptyWithCallback:(void(^)(NSArray<NSDictionary<NSString*, NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of Dictionaries of type <string, string> with value [{'1': 'one', '2': 'two', '3': 'three'}, null, {'7': 'seven', '8': 'eight', '9': 'nine'}].
 *
 * @param callback A block where NSArray<NSDictionary<NSString*, NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDictionaryItemNullWithCallback:(void(^)(NSArray<NSDictionary<NSString*, NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of Dictionaries of type <string, string> with value [{'1': 'one', '2': 'two', '3': 'three'}, {}, {'7': 'seven', '8': 'eight', '9': 'nine'}].
 *
 * @param callback A block where NSArray<NSDictionary<NSString*, NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDictionaryItemEmptyWithCallback:(void(^)(NSArray<NSDictionary<NSString*, NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of Dictionaries of type <string, string> with value [{'1': 'one', '2': 'two', '3': 'three'}, {'4': 'four', '5': 'five', '6': 'six'}, {'7': 'seven', '8': 'eight', '9': 'nine'}].
 *
 * @param callback A block where NSArray<NSDictionary<NSString*, NSString*>*> is a result object and AZOperationError is nil, if the operation is successful
 */
- (void)getDictionaryValidWithCallback:(void(^)(NSArray<NSDictionary<NSString*, NSString*>*>*, AZOperationError*))callback;

/**
 * Get an array of Dictionaries of type <string, string> with value [{'1': 'one', '2': 'two', '3': 'three'}, {'4': 'four', '5': 'five', '6': 'six'}, {'7': 'seven', '8': 'eight', '9': 'nine'}].
 *
 * @param arrayBody the NSArray<NSDictionary<NSString*, NSString*>*> value
 * @param callback A block where AZOperationError is nil if the operation is successful
 * @throws IllegalArgumentException if a required parameter is not provided.
 */
- (void)putDictionaryValidWithArrayBody:(NSArray<NSDictionary<NSString*, NSString*>*> *)arrayBody withCallback:(void(^)(AZOperationError*))callback;

@end

/**
* The protocol implementation
*/
@class ARR_AutoRestSwaggerBATArrayServiceService;

@interface ARR_Arrays : NSObject <ARR_ArraysProtocol>
@property (readonly) ARR_AutoRestSwaggerBATArrayServiceService *service;
- (instancetype)initWithService:(ARR_AutoRestSwaggerBATArrayServiceService *)service;
@end
