/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#include <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for ARR_FooEnum.
 */
@interface ARR_FooEnum : NSObject <AZStringEnum>
+ (NSArray*)values;
+ (NSString *)toStringValue:(ARR_FooEnum *)value;
@property (class, readonly) ARR_FooEnum *FOO1;
@property (class, readonly) ARR_FooEnum *FOO2;
@property (class, readonly) ARR_FooEnum *FOO3;
@end
