/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ARR_Error.h"

@implementation ARR_Error
- (void)encodeWithCoder:(id<AZCoder>)encoder {

    [encoder encodeObject:self.status forKey:@"status"];
    [encoder encodeObject:self.message forKey:@"message"];
}
- (nullable instancetype)initWithDecoder:(id<AZCoder>)decoder {

    if (self = [super init]) {
        _status = [decoder decodeObjectForKey:@"status" objectClass:[AZInteger class]];
        _message = [decoder decodeObjectForKey:@"message" objectClass:[NSString class]];
    }
    return self;
}
@end
