/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


#import "AutoRestSwaggerBATFileService.h"

/**
 * Initializes a new instance of the AutoRestSwaggerBATFileService class.
 */
@implementation AutoRestSwaggerBATFileService

    - (instancetype) init {
        if (self = [super init]) {
            
            _DEFAULT_BASE_URL = @"http://localhost:3000";
        }
        
        return self;
    }

    + (id<AutoRestSwaggerBATFileServiceProtocol>) create {
        AutoRestSwaggerBATFileService* client = [[AutoRestSwaggerBATFileService alloc] init];
        return client;
    }


    /**
     * The Files object to access its operations.
     */
    - (id<FilesProtocol>) files {
         id<FilesProtocol> op = [[Files alloc] initWithService: self];
         return op;
    }



@end
