/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "ArrayWrapper.h"

@implementation ArrayWrapper

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.array forKey: @"array"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.array = [decoder decodeArrayForKey:@"array" elementClass:[NSString class]];
    }

    return self;
}

@end
