/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "CMYKColors.h"

/**
 * The Basic model.
*/
@interface Basic : NSObject <Codable>

    /**
     * Basic Id.
    */
    // json "id"
    @property AZInteger* idProperty;

    /**
     * Name property with a very long description that does not fit on a single
     * line and a line break.
    */
    // json "name"
    @property NSString* name;

    /**
     * Possible values include: 'cyan', 'Magenta', 'YELLOW', 'blacK'.
    */
    // json "color"
    @property CMYKColors* color;


@end
