/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Basic.h"

@implementation Basic

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.idProperty forKey: @"id"];
    [encoder encodeObject: self.name forKey: @"name"];
    [encoder encodeObject: self.color forKey: @"color"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.idProperty = [decoder decodeObjectForKey:@"id" objectClass:[AZInteger class]];
        self.name = [decoder decodeObjectForKey:@"name" objectClass:[NSString class]];
        self.color = [decoder decodeObjectForKey:@"color" objectClass:[CMYKColors class]];
    }

    return self;
}

@end
