/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The BooleanWrapper model.
*/
@interface BooleanWrapper : NSObject <Codable>

    /**
     * The fieldTrue property.
    */
    // json "field_true"
    @property AZBoolean* fieldTrue;

    /**
     * The fieldFalse property.
    */
    // json "field_false"
    @property AZBoolean* fieldFalse;


@end
