/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The ByteWrapper model.
*/
@interface ByteWrapper : NSObject <Codable>

    /**
     * The field property.
    */
    // json "field"
    @property AZByteArray* field;


@end
