/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "Pet.h"
#import "Dog.h"

/**
 * The Cat model.
*/
@interface Cat : Pet <Codable>

    /**
     * The color property.
    */
    // json "color"
    @property NSString* color;

    /**
     * The hates property.
    */
    // json "hates"
    @property NSArray<Dog*>* hates;


@end
