/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Cat.h"

@implementation Cat

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject: self.color forKey: @"color"];
    [encoder encodeObject: self.hates forKey: @"hates"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

        self.color = [decoder decodeObjectForKey:@"color" objectClass:[NSString class]];
        self.hates = [decoder decodeArrayForKey:@"hates" elementClass:[Dog class]];
    }

    return self;
}

@end
