/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for CMYKColors.
 */
@interface CMYKColors : NSString <StringEnum>

    + (NSArray*) values;

    @property (class, readonly) CMYKColors* CYAN;
    @property (class, readonly) CMYKColors* MAGENTA;
    @property (class, readonly) CMYKColors* YELLOW;
    @property (class, readonly) CMYKColors* BLACK;

@end
