/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Cookiecuttershark.h"

@implementation Cookiecuttershark

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

    }

    return self;
}

@end
