/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Datetimerfc1123Wrapper.h"

@implementation Datetimerfc1123Wrapper

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.field forKey: @"field"];
    [encoder encodeObject: self.now forKey: @"now"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.field = [decoder decodeObjectForKey:@"field" objectClass:[DateTimeRfc1123 class]];
        self.now = [decoder decodeObjectForKey:@"now" objectClass:[DateTimeRfc1123 class]];
    }

    return self;
}

@end
