/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The Datetimerfc1123Wrapper model.
*/
@interface Datetimerfc1123Wrapper : NSObject <Codable>

    /**
     * The field property.
    */
    // json "field"
    @property DateTimeRfc1123* field;

    /**
     * The now property.
    */
    // json "now"
    @property DateTimeRfc1123* now;


@end
