/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The DatetimeWrapper model.
*/
@interface DatetimeWrapper : NSObject <Codable>

    /**
     * The field property.
    */
    // json "field"
    @property DateTime* field;

    /**
     * The now property.
    */
    // json "now"
    @property DateTime* now;


@end
