/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The DateWrapper model.
*/
@interface DateWrapper : NSObject <Codable>

    /**
     * The field property.
    */
    // json "field"
    @property Date* field;

    /**
     * The leap property.
    */
    // json "leap"
    @property Date* leap;


@end
