/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Dog.h"

@implementation Dog

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject: self.food forKey: @"food"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

        self.food = [decoder decodeObjectForKey:@"food" objectClass:[NSString class]];
    }

    return self;
}

@end
