/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "DurationWrapper.h"

@implementation DurationWrapper

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.field forKey: @"field"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.field = [decoder decodeObjectForKey:@"field" objectClass:[AZTimeSpan class]];
    }

    return self;
}

@end
