/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Error.h"

@implementation Error

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.status forKey: @"status"];
    [encoder encodeObject: self.message forKey: @"message"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.status = [decoder decodeObjectForKey:@"status" objectClass:[AZInteger class]];
        self.message = [decoder decodeObjectForKey:@"message" objectClass:[NSString class]];
    }

    return self;
}

@end
