/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "FloatWrapper.h"

@implementation FloatWrapper

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.field1 forKey: @"field1"];
    [encoder encodeObject: self.field2 forKey: @"field2"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.field1 = [decoder decodeObjectForKey:@"field1" objectClass:[AZDouble class]];
        self.field2 = [decoder decodeObjectForKey:@"field2" objectClass:[AZDouble class]];
    }

    return self;
}

@end
