/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The FloatWrapper model.
*/
@interface FloatWrapper : NSObject <Codable>

    /**
     * The field1 property.
    */
    // json "field1"
    @property AZDouble* field1;

    /**
     * The field2 property.
    */
    // json "field2"
    @property AZDouble* field2;


@end
