/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * Defines values for GoblinSharkColor.
 */
@interface GoblinSharkColor : NSString <StringEnum>

    + (NSArray*) values;

    @property (class, readonly) GoblinSharkColor* PINK;
    @property (class, readonly) GoblinSharkColor* GRAY;
    @property (class, readonly) GoblinSharkColor* BROWN;

@end
