/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "Shark.h"
#import "GoblinSharkColor.h"

/**
 * The Goblinshark model.
*/
    //JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
    //JsonTypeName("goblin")
@interface Goblinshark : Shark <Codable>

    /**
     * The jawsize property.
    */
    // json "jawsize"
    @property AZInteger* jawsize;

    /**
     * Colors possible. Possible values include: 'pink', 'gray', 'brown'.
    */
    // json "color"
    @property GoblinSharkColor* color;


@end
