/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "GoblinSharkColor.h"

/**
 * Defines values for GoblinSharkColor.
 */
@implementation GoblinSharkColor

    + (NSArray*) values {

        static NSArray *allValues;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            allValues = @[
                @"pink",
                @"gray",
                @"brown"
            ];
        });

        return allValues;
    }

    /** Enum value pink. */
    static GoblinSharkColor* _PINK = (GoblinSharkColor*)@"pink";

    + (GoblinSharkColor*) PINK {
        return _PINK;
    }

    /** Enum value gray. */
    static GoblinSharkColor* _GRAY = (GoblinSharkColor*)@"gray";

    + (GoblinSharkColor*) GRAY {
        return _GRAY;
    }

    /** Enum value brown. */
    static GoblinSharkColor* _BROWN = (GoblinSharkColor*)@"brown";

    + (GoblinSharkColor*) BROWN {
        return _BROWN;
    }

    + (GoblinSharkColor *) fromString: (NSString *) string {
        return (GoblinSharkColor *) string;
    }

    + (NSString *) toStringValue: (id<StringEnum>) value {

        return (NSString *) value;
    }

@end
