/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Goblinshark.h"

@implementation Goblinshark

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject: self.jawsize forKey: @"jawsize"];
    [encoder encodeObject: self.color forKey: @"color"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

        self.jawsize = [decoder decodeObjectForKey:@"jawsize" objectClass:[AZInteger class]];
        self.color = [decoder decodeObjectForKey:@"color" objectClass:[GoblinSharkColor class]];
    }

    return self;
}

@end
