/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The IntWrapper model.
*/
@interface IntWrapper : NSObject <Codable>

    /**
     * The field1 property.
    */
    // json "field1"
    @property AZInteger* field1;

    /**
     * The field2 property.
    */
    // json "field2"
    @property AZInteger* field2;


@end
