/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The MyBaseType model.
*/
    //JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
    //JsonTypeName("MyBaseType")
    // SubTypes: name = "Kind1", value = MyDerivedType
// Needs Flatten
@interface MyBaseType : NSObject <Codable>

    /**
     * The propB1 property.
    */
    // json "propB1"
    @property NSString* propB1;

    /**
     * The propBH1 property.
    */
    // json "helper.propBH1"
    @property NSString* propBH1;


@end
