/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "MyBaseType.h"

@implementation MyBaseType

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.propB1 forKey: @"propB1"];
    [encoder encodeObject: self.propBH1 forKey: @"helper.propBH1"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.propB1 = [decoder decodeObjectForKey:@"propB1" objectClass:[NSString class]];
        self.propBH1 = [decoder decodeObjectForKey:@"helper.propBH1" objectClass:[NSString class]];
    }

    return self;
}

@end
