/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "MyKind.h"

/**
 * Defines values for MyKind.
 */
@implementation MyKind

    + (NSArray*) values {

        static NSArray *allValues;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            allValues = @[
                @"Kind1"
            ];
        });

        return allValues;
    }

    /** Enum value Kind1. */
    static MyKind* _KIND1 = (MyKind*)@"Kind1";

    + (MyKind*) KIND1 {
        return _KIND1;
    }

    + (MyKind *) fromString: (NSString *) string {
        return (MyKind *) string;
    }

    + (NSString *) toStringValue: (id<StringEnum>) value {

        return (NSString *) value;
    }

@end
