/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The ReadonlyObj model.
*/
@interface ReadonlyObj : NSObject <Codable>

    /**
     * The idProperty property.
    */
    // json "id", access = JsonProperty.Access.WRITE_ONLY
    @property (readonly) NSString* idProperty;

    /**
     * The size property.
    */
    // json "size"
    @property  AZInteger* size;

    /**
    * Creates an instance of ReadonlyObj class.
    */
    - (id) initIdProperty: (NSString *) idProperty;


@end
