/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Salmon.h"

@implementation Salmon

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject: self.location forKey: @"location"];
    [encoder encodeObject: self.iswild forKey: @"iswild"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

        self.location = [decoder decodeObjectForKey:@"location" objectClass:[NSString class]];
        self.iswild = [decoder decodeObjectForKey:@"iswild" objectClass:[AZBoolean class]];
    }

    return self;
}

@end
