/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "Shark.h"

/**
 * The Sawshark model.
*/
    //JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
    //JsonTypeName("sawshark")
@interface Sawshark : Shark <Codable>

    /**
     * The picture property.
    */
    // json "picture"
    @property AZByteArray* picture;


@end
