/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "Fish.h"

/**
 * The Shark model.
*/
    //JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "fishtype")
    //JsonTypeName("shark")
    // SubTypes: name = "sawshark", value = Sawshark
    // SubTypes: name = "goblin", value = Goblinshark
    // SubTypes: name = "cookiecuttershark", value = Cookiecuttershark
@interface Shark : Fish <Codable>

    /**
     * The age property.
    */
    // json "age"
    @property AZInteger* age;

    /**
     * The birthday property.
    */
    // json "birthday", required = true
    @property DateTime* birthday;

    /**
    * Creates an instance of Shark class.
    * @param birthday the birthday value.
    */
    - (id) initBirthday: (DateTime*) birthday;


@end
