/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Shark.h"

@implementation Shark

    - (id) initBirthday: (DateTime*) birthday {
        self = [super init];
        if (self) {
            _birthday = birthday;
        }
        return self;
    }

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject: self.age forKey: @"age"];
    [encoder encodeObject: self.birthday forKey: @"birthday"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

        self.age = [decoder decodeObjectForKey:@"age" objectClass:[AZInteger class]];
        self.birthday = [decoder decodeObjectForKey:@"birthday" objectClass:[DateTime class]];
    }

    return self;
}

@end
