/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>
#import "Cat.h"

/**
 * The Siamese model.
*/
@interface Siamese : Cat <Codable>

    /**
     * The breed property.
    */
    // json "breed"
    @property NSString* breed;


@end
