/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "Siamese.h"

@implementation Siamese

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject: self.breed forKey: @"breed"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

        self.breed = [decoder decodeObjectForKey:@"breed" objectClass:[NSString class]];
    }

    return self;
}

@end
