/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "SmartSalmon.h"

@implementation SmartSalmon

- (void)encodeWithCoder:(id<Coder>) encoder {

    [super encodeWithCoder:encoder];
    [encoder encodeObject: self.additionalProperties forKey: @""];
    [encoder encodeObject: self.collegeDegree forKey: @"college_degree"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super initWithDecoder:decoder]) {

        self.additionalProperties = [decoder decodeDictionaryForKey:@"" elementClass:[NSObject class]];
        self.collegeDegree = [decoder decodeObjectForKey:@"college_degree" objectClass:[NSString class]];
    }

    return self;
}

@end
