/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

#import "StringWrapper.h"

@implementation StringWrapper

- (void)encodeWithCoder:(id<Coder>) encoder {

    [encoder encodeObject: self.field forKey: @"field"];
    [encoder encodeObject: self.empty forKey: @"empty"];
    [encoder encodeObject: self.null forKey: @"null"];

}

- (nullable instancetype)initWithDecoder:(id<Coder>)decoder {

    if (self = [super init]) {

        self.field = [decoder decodeObjectForKey:@"field" objectClass:[NSString class]];
        self.empty = [decoder decodeObjectForKey:@"empty" objectClass:[NSString class]];
        self.null = [decoder decodeObjectForKey:@"null" objectClass:[NSString class]];
    }

    return self;
}

@end
