/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
*/

#import <AzureClientRuntime/AzureClientRuntime.h>

/**
 * The StringWrapper model.
*/
@interface StringWrapper : NSObject <Codable>

    /**
     * The field property.
    */
    // json "field"
    @property NSString* field;

    /**
     * The empty property.
    */
    // json "empty"
    @property NSString* empty;

    /**
     * The null property.
    */
    // json "null"
    @property NSString* null;


@end
